---
# стадии нашего pipeline. Для группировки jobs.
# Нужно помнить, что stages выполняются последовательно, а job параллельно.
stages:
  - test
  - deploy

image: node:14.17.0-alpine

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

eslint:
  stage: test
  script:
    - npm run lint

prettier:
  stage: test
  script:
    - npm run check:format

deploy:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - npm run build
    - rsync -a --progress --human-readable --delete \
      --exclude-from '.gitignore' \
      --exclude .gitignore \
      --exclude .git \
      --exclude public \
      . deploy@172.104.151.230:~/
    - ssh deploy@172.104.151.230 "pushd ~/realworld && npm install && popd && pm2 restart ecosystem.config.js"
